### ISSUE TITLE
Is "pip install pytorchvideo" or "pip install torchvideo"?

### ISSUE THREAD

**Issue by dspcad** [facebookresearch/omnivore#7]
I got an error said: 
ERROR: Could not find a version that satisfies the requirement pytorchvideo (from versions: none)
ERROR: No matching distribution found for pytorchvideo

**Comment by woctezuma** [comment]
- https://github.com/facebookresearch/SlowFast/issues/409

**Comment by mannatsingh** [comment]
Thanks for the solution @woctezuma . 

I'm guessing the environment you are using doesn't have a pre-built package available on pip. 

Installing from source (`pip install "git+https://github.com/facebookresearch/pytorchvideo.git@stable"`) is a good alternative, although there is a chance that the code doesn't work because the environment is unsupported.
